### ISSUE TITLE
Investigate ability to autowire services from the container instead of explicitly defining

### ISSUE THREAD

**Issue by asgrim** [Roave/behat-psr11extension#9]
At the moment, dependencies have to be explicitly defined in `behat.yml`. This gets tiresome quite quickly, would be nice if we can add autowiring support.

**Comment by Ocramius** [comment]
I think @afilina developed something in this direction :+1:

**Comment by afilina** [comment]
@Ocramius I leveraged this extension to autowire services using a DIC, but we still need to specify dependencies for the contexts themselves in behat.yml. I would be happy to poke around and see how this extension can also autowire contexts.

**Comment by asgrim** [comment]
@afilina ah s'all good, I wondered if you'd figured out already. No worries, I'm on it :) thanks

**Comment by asgrim** [comment]
Fixed by #13 & #14 - thanks @tkotosz !
